FROM node:14-slim

WORKDIR /usr/src/app

ENV registry http://registry.npmjs.org/
ENV http_proxy http://rb-proxy-apac.bosch.com:8080
ENV https_proxy http://rb-proxy-apac.bosch.com:8080


RUN npm config set proxy http://rb-proxy-apac.bosch.com:8080
RUN npm config set https-proxy http://rb-proxy-apac.bosch.com:8080
RUN npm config set registry http://registry.npmjs.org/
RUN npm install mongoose 

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

EXPOSE 5000

CMD ["index.js"]
